### ISSUE TITLE
Please remove unnecessary files

### ISSUE THREAD

**Issue by pcav** [sookoll/qgis_plugin_inads_geocoder#3]
.pyc etc.
They are generated automatically during installation.
Thanks.

**Comment by sookoll** [comment]
Ok, I'm still learning. .pyc etc? can you be more specific?

**Comment by pcav** [comment]
compiled Python files (*.pyc) are generated automatically upon install, so please remove them from the repo, where only corresponding *.py should be (plus of course *.ui etc.)

**Comment by sookoll** [comment]
Removed pyc files, also old icon. Replace package in plugins repository.
