### ISSUE TITLE
Please consider mergin with other plugins

### ISSUE THREAD

**Issue by pcav** [sookoll/qgis_plugin_inads_geocoder#4]
There are a number of plugins with similar if not identical functionality, for other countries. It would be good to consolidate the work of all of them into only one generalized plugin: less code, easier maintenance, a more predictable environment for users, and many other advantages.
Could you please join a discussion on qgis-dev ML?

**Comment by pcav** [comment]
See e.g. 
https://lists.osgeo.org/pipermail/qgis-developer/2016-June/043145.html

**Comment by sookoll** [comment]
Good point, but this plugin is for Estonian users mainly, so merging it with other generic plugin will make usage of this more complicated for users. I don't mind if this plugin will never be part of QGIS plugin repository because of this. I can share it other ways.

**Comment by pcav** [comment]
Could you please follow the discussion in mailing list? I think it is very interesting, and your input could be useful there.
I do not mind publishing, I'm just trying to further improve the situation.
Thanks.
